### PR TITLE
feat(products): add delete product request, add status enum `deleted`

### PR DESCRIPTION
**Pull request by lehuygiang28**
- update product status, for management need to pass a query `select_type=both_deleted_and_active` to get both. By default just get the active product

### CODE REVIEW

**Comment by lehuygiang28** [comment]
@bou2201 alo alo did u see this commnent ?

**Comment by lehuygiang28** [comment]
@lehuygiang28

**Comment by bou2201** [comment]
yah

**Comment by lehuygiang28** [comment]
> yah
@bou2201 

ok đấy, pr này update thêm status deleted của product nhé
thêm nữa là mặc định sẽ chỉ lấy active product, muốn lấy cả 2 thì truyền query nhớ

**Pull request merged**
